(module
  (func (result i32)
    (block (result i32)
      (i32.const 1)
      (loop (result i32)
        (if (result i32)
          (i32.const 2)
          (then (i32.const 3))
          (else (i32.const 4))
        )
      )
      (drop)
    )
  )
)